version: "3.8"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /media_rollout/appdata/radarr:/config
      - /media_rollout/storage/movies:/movies
      - /media_rollout/storage/downloads:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /media_rollout/appdata/sonarr:/config
      - /media_rollout/storage/tv:/tv
      - /media_rollout/storage/downloads:/downloads

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 1024M
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /media_rollout/appdata/lidarr:/config
      - /media_rollout/storage/music:/music
      - /media_rollout/storage/downloads:/downloads

  nzbhydra2:
    container_name: nzbhydra2
    image: linuxserver/nzbhydra2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 1024M
    ports:
      - 5076:5076
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /media_rollout/appdata/nzbhydra2:/config

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 1024M
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /media_rollout/appdata/sabnzbd:/config
      - /media_rollout/storage/downloads:/downloads:rw

networks:
  default:
    name: media-rollout
